### PR TITLE
Added most options as commandline options with argparse.

### PR DESCRIPTION
**Pull request by kellya**
I'm a CLI guy...so I wanted to enhance this by specifying options on the command line.  So it's easy to extend sets, colors, background, etc by just specifying them on the command line rather than extending code.

### CODE REVIEW

**Review by bannyvishwas — CHANGES_REQUESTED** [review]
hi kellya.. really good job.. but the generated document text can be in multiple color according to the user.. so arg "lettercolor" will not work here.. then it will generate everything in single color.. Remove the lettercolor argument.. then it will be fine.. we will get color of the text from input file. Thanks..

**Comment by kellya** [comment]
I have removed the lettercolor option

**Review by bannyvishwas — APPROVED** [review]
I removed letter_set arg just to preserve the letter variation to the document.. nice job Kellya..

**Review by bannyvishwas — APPROVED** [review]
corrected missing ")" in help arg

**Pull request merged**
